name: Publish

on:
  push:
    branches:
      - main

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Goby executable
      run: go build -o goby cmd/goby/main.go
    - name: List the Goby executable
      run: ls -l
    - name: Upload the Goby binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ./goby
